### ISSUE TITLE
Epic - Ajuste de funcionalidades

### ISSUE THREAD

**Issue by sigespweb22** [sigespweb22/sigespweb-app#26]
Requisito levantados para criação e ajuste de funcionalidades:

→Ajustar para permitir agendar reforço para o mês seguinte;
→Notificação de data disponibilizada dinamicamente, após cancelamento de reforço;
→Sábado/Domingo é Limitado??!?;
→Como vamos limitar total de vagas por dia?
→Criar parâmetro de mínimo de vagas de reforço necessário por plantão dia (afim de respeitar a necessidade de demanda de forma dinâmica);
→Sendo assim, permitir agenda de reforço somente para estes dias pré determinados, de acordo com o número de vagas determinadas por plantão.
→Servidor com licença prêmio e férias, deverá ter prioridade para marcação de
todos os reforços do mês seguinte.
→Manter dinamica para criar o limite de vagas por dia, separando somente
por limite de vagas à noite e à tarde.
Limite 6 quem faz dia;
Limite 3 quem faz dia;
→Criar Edi para importação dos servidores de férias...

Permitir excluir qualquer reforço

**Comment by sigespweb22** [comment]
Separar as issues de acordo com a lista abaixo:

- [ ] - [ ] Ao logar usuário servidor do estado deverá ver somente o calendário do mês seguinte ao atual para agendar seus reforços;
- [ ] Criar notificação de data disponibilizada após cancelamento do reforço
- [ ] Ao criar regra deverá permitir informar o limite de vaga de marcação por dia por turno de reforço, considerando o limite padrão de 6 para o período matutino/vespertino, e 3 vagas para o período noturno.
- [ ] Criar EDI para importar planilha de férias e licença prêmio
- [ ] Ajustar cadastro de servidor para que seja possível informar período de gozo de férias e licença prêmio;
- [ ] Ajustar regra de limite de marcação: Servidor com licença prêmio ou férias agendada para o mês da marcação do reforço pode agendar até 4 reforços, e o último permitir somente na última janela.
- [ ] Ajustar regra de marcação de reforço: Verificar limite de vagas para o dia e turno proposto para marcação.
- [ ] Ajustar para permitir excluir qualquer reforço marcado.

**Comment by sigespweb22** [comment]
Concluído em issues menores
